### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by Impeta** [dylanhthomas/qwinff#1]
Is this forked project abandoned? QWinFF suits me up pretty well, so would love if this could be continued!

**Comment by dylanhthomas** [comment]
It is not abandoned, I've just been busy at work. I have it building from the command line consistently and am about ready to release it before starting work on the improvements.

**Comment by dylanhthomas** [comment]
@Impeta I just uploaded the first release for Windows 64-bit portable https://github.com/dylanhthomas/qwinff/releases/tag/v1.0.0
